name: referral_hero_flutter
description: "A Flutter plugin for integrating ReferralHero API to manage referrals, contests, and rewards in your mobile applications."
version: 0.0.2
homepage: https://github.com/maitre-app/ReferralHero-Flutter
repository: https://github.com/maitre-app/ReferralHero-Flutter
issue_tracker: https://github.com/maitre-app/ReferralHero-Flutter/issues
documentation: https://support.referralhero.com/

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  device_info_plus: ^10.1.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.referral_hero_flutter
        pluginClass: ReferralHeroFlutterPlugin
      ios:
        pluginClass: ReferralHeroFlutterPlugin

